### ISSUE TITLE
Jest - The integration fails when running tests concurrently 

### ISSUE THREAD

**Issue by pritishGalway** [reportportal/agent-js-jest#147]
Hello, 

Seeing the following error when the jest tests are run concurrently. 

```
2024-07-17T10:44:49.6007981Z Error: Item with tempId "405gzmgklypptxtq" not found
2024-07-17T10:44:49.6012705Z     at RPClient.finishTestItem (/__w/qe-api-integration/qe-api-integration/node_modules/@reportportal/client-javascript/lib/report-portal-client.js:589:9)
2024-07-17T10:44:49.6019481Z     at JestReportPortal._finishPassedStep (/__w/qe-api-integration/qe-api-integration/node_modules/@reportportal/agent-js-jest/src/reporter.js:218:37)
2024-07-17T10:44:49.6025718Z     at JestReportPortal._finishStep (/__w/qe-api-integration/qe-api-integration/node_modules/@reportportal/agent-js-jest/src/reporter.js:206:14)
2024-07-17T10:44:49.6032194Z     at JestReportPortal.onTestCaseResult (/__w/qe-api-integration/qe-api-integration/node_modules/@reportportal/agent-js-jest/src/reporter.js:79:10)
2024-07-17T10:44:49.6038766Z     at ReporterDispatcher.onTestCaseResult (/__w/qe-api-integration/qe-api-integration/node_modules/@jest/core/build/ReporterDispatcher.js:64:24)
2024-07-17T10:44:49.6044478Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

The error resolves when running the tests serially using `--detectOpenHandles`, `-i` or `--runInBand` options. 

Current versions:
```
"@reportportal/agent-js-jest": "^5.1.0"
"jest": "^29.7.0"
```

The issue could be a duplicate of https://github.com/reportportal/agent-js-jest/issues/146
However, the error is happening at a different place in code for them.

**Comment by aviadhadidainx** [comment]
It is not supported based yet on the docs:
![image](https://github.com/user-attachments/assets/64b57b02-6bef-4467-b818-70239b4f1c9e)

**Comment by pritishGalway** [comment]
We are not using `test.concurrent` which I believe runs tests concurrently within the same test file. In our case, in the default setting, test files are run concurrently.

**Comment by lucas-delafuente-deel** [comment]
Hi team! 
We have the same issue 🥲  and we are using the same version as you.
Additionally, I think this error causes our executions to never finish in report portal and remain running.
 
 Any idea about a solution 🙏 ?

**Comment by lucas-delafuente-deel** [comment]
Hi team!
We have the same issue 🥲 and we are using the same version as you.
Additionally, I think this error causes our executions to never finish in report portal and remain running.

Any idea about a solution 🙏 ?

**Comment by lucas-delafuente-deel** [comment]
Woow, that is amazing, thank you! I will keep my eyes on that PR.

**Comment by AmsterGet** [comment]
Fixed in [v5.1.1](https://github.com/reportportal/agent-js-jest/releases/tag/v5.1.1).
Huge thanks, @tristanzander !

**Comment by owens-ben** [comment]
I'm not sure this issue is resolved. I see it when running parallel tests in 5.1.1

**Comment by nishant-shah-social** [comment]
I am too experiencing this problem in 5.1.1

**Comment by AmsterGet** [comment]
Hello guys!

Try the latest version [5.1.2](https://github.com/reportportal/agent-js-jest/releases/tag/v5.1.2), which is supposed to fix the mentioned suites issues.
Please let me know if everything now works as expected.
I look forward to your feedback!

**Comment by lucas-delafuente-deel** [comment]
Hi Amster, thanks, I will try to change the version, thanks!

**Comment by nishant-shah-social** [comment]
I tried with 5.1.2. But, somehow I still faced the same issue.

**Comment by AmsterGet** [comment]
Hello @nishant-shah-social !
Could you please provide a reproducible sample with this issue?

**Comment by AmsterGet** [comment]
Hello guys!

Please take a look at [v5.1.3](https://github.com/reportportal/agent-js-jest/releases/tag/v5.1.3).
Please check out the fix and let me know if it helps!
